### ISSUE TITLE
Magnetic variation not present on some positions

### ISSUE THREAD

**Issue by StevePirateX** [vatSys/australia-dataset#144]
When opperating on some positions (enroute and oceanic). The distance bearing tool does not show the heading the aircraft would fly if it was to follow the line.

For example, if using the Bindook position, the bearing for the centreline for 16R is 168 and not 155. This means that if you give a pilot a heading based off the bearing line tool, it will not be correct.

![magvar-issue](https://github.com/user-attachments/assets/ea72c8bb-163b-444e-9ccb-14d281860274)

**Comment by Slep-wt** [comment]
#145 Merged into 2411draft. Cheers Steve :)

**Comment by Slep-wt** [comment]
Hi Steven,

Unfortunately after further consultation with Subject Matter Experts, the behaviour you have described is indeed intentional. 

Due to the nature of the Eurocat implementation vatSys provides, a single magnetic variation can only be applied to a single positon, akin to the real world.

Since enroute positions cover a large area, applying these magnetic variations to improve vectoring accuracy within the TMA would unintentionally make vectoring less accurate elsewhere.

This issue is again an intended feature of TAAATS, as Enroute controllers are not expected nor permitted to provide control services within a TMA in the real world.

Cheers,
Rakshan
